type User {
	UUID: String
	Name: String
	Posts: [Post]
}

type Post {
	UUID: String
	Text: String
}

input UserInput {
	Name: String
	Posts: [PostInput]
}

input PostInput {
	Text: String
}

type Mutation {
	createUser(input: UserInput!): User
}

type Query {
	getUser(uuid: String!): User
}

schema {
	query: Query
	mutation: Mutation
}
